// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/collection-log': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/collection-log.post').default>>>>
    }
    '/api/progress-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/api/progress-image.post').default>>>>
    }
    '/getCollectionLogItem': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/getCollectionLogItem.post').default>>>>
    }
    '/getImage': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/getImage.post').default>>>>
    }
    '/': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/index.get').default>>>>
    }
    '/osrs/equipment/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/osrs/equipment/[id].get').default>>>>
    }
    '/osrs/equipment': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/osrs/equipment/index.get').default>>>>
    }
    '/osrs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/osrs/index.get').default>>>>
    }
    '/osrs/items/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/osrs/items/[id].get').default>>>>
    }
    '/osrs/items': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/osrs/items/index.get').default>>>>
    }
    '/osrs/monsters/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/osrs/monsters/[id].get').default>>>>
    }
    '/osrs/monsters': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/osrs/monsters/index.get').default>>>>
    }
    '/osrs/prayers/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/osrs/prayers/[id].get').default>>>>
    }
    '/osrs/prayers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/osrs/prayers/index.get').default>>>>
    }
    '/osrs/search/:type': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/osrs/search/[type].get').default>>>>
    }
    '/osrs/weapons/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/osrs/weapons/[id].get').default>>>>
    }
    '/osrs/weapons': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/osrs/weapons/index.get').default>>>>
    }
  }
}
export {}